#!/bin/python3
Given an integer, , perform the following conditional actions:

If  is odd, print Weird
If  is even and in the inclusive range of  to , print Not Weird
If  is even and in the inclusive range of  to , print Weird
If  is even and greater than , print Not Weird

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
# if n modulus 2 not equal to 0 then print weird
    if n % 2 !=0:
        print("Weird")
# if n modulus 2 equal 0 and n equal or more than 2 but equal or less than 5 then it is not weird
    elif n % 2 == 0 and  2 <= n <= 5:
        print("Not Weird")
    elif n % 2 == 0 and 2 <= n <= 20:
        print("Weird")
    else:
        print("Not Weird")
